### ISSUE TITLE
No tagged stable release

### ISSUE THREAD

**Issue by thomaswelton** [JDare/Acetone#2]
Please create a new tagged release (once https://github.com/JDare/Acetone/pull/1 is merged)

The default minimum stability on Laravel 4.1 is stable, not dev. So out of the box people will not be able to install this package without changing their minimum stability settings.
And I am one of those people who don't want to install the bleeding edge of all my packages.

Thanks

**Comment by thomaswelton** [comment]
@JDare bump, merging this PR and tagging a new release can all be done in 2mins from a smartphone :)

**Comment by JDare** [comment]
Tagged v 1.0.0
